baseURL = 'https://korrawit.me/'
languageCode = 'en-us'
title = 'Korrawit Y.'
theme = "archie"
googleAnalytics = "UA-209830055-1"
copyright = "© korrawit"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = '"Tell me and I forget, teach me and I may remember, involve me and I learn." — Benjamin Franklin'

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
  
# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/korrawit"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/ykorrawit"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
